name: taxi_trips
version: '1.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

models:
  taxi_trips:
    staging:
      materialized: view
    marts:
      materialized: table
