version: 2
sources:
  - name: source_data
    schema: main  # Explicitly tell dbt the source table is in main schema
    tables:
      - name: taxi_trips

models:
  - name: stg_taxi_trips
    description: Filter invalid trips
    columns:
    - name: pickup_datetime
      tests:
        - not_null

    - name: dropoff_datetime
      tests:
        - not_null

    - name: payment_type
      tests:
        - accepted_values:
            values: [1, 2, 3, 4, 5, 6]

    - name: rate_code_id
      tests:
        - accepted_values:
            values: [1, 2, 3, 4, 5, 6]
  - name: mart_trip_summary
    description: Daily trip summaries
